### ISSUE TITLE
The last `curry` example seems broken

### ISSUE THREAD

**Issue by Ltrlg** [DerFlatulator/es-function-partial-curry#2]
If I understand it correctly (and an execution with the polyfill agrees), the last expression is evaluated as follows:
- `translateX(translateY(-1), 1)`
- `translateX(translate(0)(-1)(), 1)`
- `translateX(origin.translated(0,-1), 1)`
- `translateX(Point{0,-1}, 1)`
- `translate(Point{0,-1})(0)()` (second parameter `1` ignored by `translateX`)
- `Point{0 + Point{0,-1}, 0}`

The `x` property of the final object is the string `'0[object Object]'` and the `y` property is 0, which does not match the comment, `x: 1, y: -1`.

**Comment by azz** [comment]
Quite right. That example was a poor use of currying anyway. I have replaced it with a more interesting example involving lazy stacks. Thanks for the catch.

---

(New example, for reference)

``` js
class Stack {
  constructor(...vals) {
    this._list = [...vals];
  }
  push(...vals) {
    return new Stack(...this._list, ...vals);
  }

  pop() { return new Stack(...this._list.slice(0, -1)); }
  top() { return this._list.slice(-1); }

  toString() { return this._list.toString(); }
}

const stack = new Stack(1, 2, 3);

function lazilyAddItems(items) {
  if (!items.length) return this;
  return this(...items);
}

const curriedPush = Stack.prototype.push.curry()
  ::lazilyAddItems([4, 5, 6])
  ::lazilyAddItems([7, 8, 9]);

const stack2 = stack::curriedPush(); // late binding (curried.call(stack))
console.log(stack2.toString()) //=> 1,2,3,4,5,6,7,8,9

const stack3 = (new Stack)::curriedPush();
console.log(stack3.toString()) //=> 4,5,6,7,8,9

console.log(stack.toString()) //=> 1,2,3 (immutable)
```
